# Generated by Django 4.0.4 on 2022-05-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petboarding',
            name='pet_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_boarding', to='shop.pets'),
        ),
        migrations.AlterField(
            model_name='petgrooming',
            name='pet_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_grooming', to='shop.pets'),
        ),
        migrations.AlterField(
            model_name='petwalking',
            name='pet_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pets'),
        ),
    ]
